#ifndef FLIGHT_CONTROLLER_H_
#define FLIGHT_CONTROLLER_H_

#define SERVER_NAME "flight_controller"
#define MAX_STRING_LEN 64
#define SHM_NAME "data"
#define PAGE_SIZE 4096
#define _PULSE_CODE_UPDATE_SPEED1 1
#define _PULSE_CODE_UPDATE_SPEED2 2
#define _PULSE_CODE_UPDATE_SPEED3 3
#define _PULSE_CODE_UPDATE_SPEED4 4

#endif /* FLIGHT_CONTROLLER_H_ */
