#ifndef FLIGHT_CONTROLLER_H_
#define FLIGHT_CONTROLLER_H_

#define SERVER_NAME "flight_controller"
#define MAX_STRING_LEN 128
#define SHM_NAME "data"
#define PAGE_SIZE 4096

// PULSE CODES
#define _PULSE_CODE_UPDATE_SPEED1 (_PULSE_CODE_MINAVAIL + 1)
#define _PULSE_CODE_UPDATE_SPEED2 (_PULSE_CODE_MINAVAIL + 2)
#define _PULSE_CODE_UPDATE_SPEED3 (_PULSE_CODE_MINAVAIL + 3)
#define _PULSE_CODE_UPDATE_SPEED4 (_PULSE_CODE_MINAVAIL + 4)

// MESSAGE CODES

#endif /* FLIGHT_CONTROLLER_H_ */
